---
- name: Install deps(Arch)
  action: >
    {{ansible_pkg_mgr}} name={{item}}
  with_items:
    - fish
    - git
    - grc
    - fzf
    - fasd
  become: yes
  become_user: root
  when: ansible_distribution == 'Archlinux'

- name: Add deps repos(Ubuntu)
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - 'ppa:fish-shell/release-2'
    - 'ppa:git-core/ppa'
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'

- name: Install deps(Ubuntu)
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - fish
    - git
    - grc
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'

- name: Create config directory for fish
  file:
    path: "{{ ansible_env.HOME }}/.config/fish/functions"
    state: directory

- name: Download fisherman
  get_url:
    url: https://raw.githubusercontent.com/fisherman/fisherman/master/fisher.fish
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"

- name: Install fisher plugins
  shell: fisher {{item}}
  args:
    executable: /usr/bin/fish
  with_items:
    - omf/theme-cbjohnson
    - omf/fasd
    - fzf
    - omf/grc
    - pbcopy

- name: Setup fish config
  copy: src=config.fish dest="{{ ansible_env.HOME }}/.config/fish/config.fish"

- name: set up fish as default shell
  user: name={{ansible_user_id}} shell=/usr/bin/fish
  become: yes
  become_user: root
...
