---
- name: Install dependencies
  package: name={{item}} state=present
  with_items:
    - zsh
    - curl
    - autojump
  become: yes
  become_user: root
  when: ansible_os_family != 'Darwin'

- name: Install dependencies
  command: brew install {{item}}
  with_items:
    - zsh
    - autojump
  when: ansible_os_family == 'Darwin'

- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest={{ansible_user_dir}}/.oh-my-zsh

- name: set up oh-my-zsh config
  template: src=zshrc.j2 dest={{ansible_user_dir}}/.zshrc

- name: set up zsh-syntax-highlighting
  git: repo=https://github.com/zsh-users/zsh-syntax-highlighting.git dest={{ansible_user_dir}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: download fzf
  git: repo=https://github.com/junegunn/fzf dest={{ansible_env.HOME}}/.fzf

- name: install fzf
  command: "{{ansible_env.HOME}}/.fzf/install --all --64"

- name: download zsh-autocompletion
  git: repo=https://github.com/zsh-users/zsh-autosuggestions dest={{ansible_user_dir}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: set up zsh as default shell
  user: name={{ansible_user_id}} shell=/bin/zsh
  become: yes
  become_user: root
  when: ansible_os_family != 'Darwin'
...
