---
# - name: Install i3 and deps
  # command: "pacman -S {{item}}"
  # with_items:
    # - i3-wm
    # - xautolock
    # - i3lock
    # - rofi
    # - urxvt
    # - nitrogen
    # - redshift
  # become: yes
  # udecome_user: root

- file:
    path: "{{ansible_user_dir}}/.config/i3"
    state: directory

- name: set up config
  template: src=config dest="{{ansible_user_dir}}/.config/i3/config"

- name: set up Xresources
  template: src=.Xresources dest="{{ansible_user_dir}}/.Xresources"
...
