---
- name: Install git
  package: name=git state=present
  become: yes
  become_user: root
  when: ansible_os_family != 'Darwin'

- name: Install git on Mac
  command: brew install git
  when: ansible_os_family == 'Darwin'

- name: Set up global gitignore conf
  template: src=gitignore_global dest={{ansible_user_dir}}/.gitignore_global

- name: Configure git to use global gitignore
  git_config: name=core.excludesfile scope=global value="{{ansible_user_dir}}/.gitignore_global"
...
