# - name: Add deps repos(Ubuntu)
#   apt_repository:
#     repo: "ppa:webupd8team/atom"
#     state: present
#   become: yes
#   become_user: root
#   when: ansible_distribution == 'Ubuntu'

- name: Install deps(Arch)
  action: >
    {{ansible_pkg_mgr}} name=atom
  become: yes
  become_user: root

- name: copy keymap file
  copy: src=keymap.cson dest="{{ ansible_env.HOME }}/.atom/keymap.cson"

- name: install all deps
  shell: "apm install {{item}}"
  with_items:
    # - cursor-history
    # - vim-mode-plus
    # - vim-mode-plus-move-to-symbols
    - atom-beautify
    - atom-typescript
    - autocomplete-plus
    - busy-signal
    - editorconfig
    - file-icons
    - fuzzy-finder
    - git-plus
    - highlight-selected
    - hyperclick
    - intentions
    - language-docker
    - language-javascript-jsx
    - language-latex
    - language-smalltalk
    - linter
    - linter-eslint
    - linter-golinter
    - linter-pylint
    - linter-tslint
    - linter-ui-default
    - minimap
    - permanent-delete
    - tabs-to-spaces
    - zentabs
