---
- name: install tmux
  action: >
    {{ansible_pkg_mgr}} name=tmux
  become: yes
  become_user: root

- name: set up tmux config
  template: src=tmux.conf dest={{ansible_user_dir}}/.tmux.conf 
...
