---
- name: Install vim
  action: >
    {{ansible_pkg_mgr}} name=vim
  become: yes
  become_user: root

- name: set up vim config
  copy: src=vimrc dest={{ansible_user_dir}}/.vimrc

- name: Install deps(Ubuntu)
  action: >
    {{ansible_pkg_mgr}} name={{item}}
  become: yes
  become_user: root
  with_items:
    - exuberant-ctags
    - xsel
  when: ansible_distribution == 'Ubuntu'

- name: Install Ctags(Archlinux)
  action: >
    {{ansible_pkg_mgr}} name={{item}}
  become: yes
  become_user: root
  with_items:
    - ctags
    - xsel
  when: ansible_distribution == 'Archlinux'

- name: set up ctags config
  copy: src=ctags dest={{ansible_user_dir}}/.ctags

- name: Install Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest={{ansible_user_dir}}/.vim/bundle/Vundle.vim

- name: Install Vundle Plugins
  command: vim -E -s -c "source {{ansible_user_dir}}/.vimrc" -c PluginInstall -c qa 
  ignore_errors: true

#- name: Compile YouCompleteMe
  #command: "{{ansible_user_dir}}/.vim/bundle/YouCompleteMe/install.py --clang-completer"
...
