---
- name: Install vim
  package: name=vim state=present
  become: yes
  become_user: root
  when: ansible_os_family != 'Darwin'

- name: Install vim on Mac
  command: brew install vim
  when: ansible_os_family == 'Darwin'

- name: Set up vim config
  copy: src=vimrc dest={{ansible_user_dir}}/.vimrc

- name: Install ctags
  package: name={{item}} state=present
  with_items:
    - ctags
    - xsel
  become: yes
  become_user: root
  when: ansible_os_family != 'Darwin'

- name: Install ctags on Mac
  command: brew install ctags
  when: ansible_os_family == 'Darwin'

- name: Set up ctags config
  copy: src=ctags dest={{ansible_user_dir}}/.ctags

- name: Install Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest={{ansible_user_dir}}/.vim/bundle/Vundle.vim

- name: Install Vundle Plugins
  command: vim -E -s -c "source {{ansible_user_dir}}/.vimrc" -c PluginInstall -c qa
  ignore_errors: true

#- name: Compile YouCompleteMe
  #command: "{{ansible_user_dir}}/.vim/bundle/YouCompleteMe/install.py --clang-completer"
...
